### ISSUE TITLE
Cargo cost Overflow.

### ISSUE THREAD

**Issue by Rumialumia** [BattletechModders/IttyBittyLivingSpace#2]
[itty_bitty_living_space.log](https://github.com/IceRaptor/IttyBittyLivingSpace/files/3243154/itty_bitty_living_space.log)
![20190531193342_1](https://user-images.githubusercontent.com/3081919/58740203-fe0fc180-83dc-11e9-825e-49cbb48b8f19.jpg)
When I started a new campaign all my mechs equipment has a overflowed cargo cost. Will do some testing and figure out if its just a visual bug or and more problematic one.

**Comment by IceRaptor** [comment]
This is fixed in 0.5.0, available on https://github.com/IceRaptor/IttyBittyLivingSpace/releases/tag/REL_0.5.0. I appreciate you taking the time to report this!
